# Generated by Django 4.1 on 2022-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
