# Generated by Django 4.1 on 2022-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_orderline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("vender", "vender"), ("customer", "customer")], max_length=15
            ),
        ),
    ]
