# Generated by Django 4.1 on 2022-09-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="highlight1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="highlight2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="highlight3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="highlight4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
