# Generated by Django 4.1 on 2022-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_address_address_alter_address_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
    ]
