# Generated by Django 4.1 on 2022-09-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_order_amount_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
