# Generated by Django 4.1 on 2022-09-16 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_covered_in_product_domestic_war_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("min", "min"),
                            ("bank", "bank"),
                            ("category", "category"),
                            ("sub_cat", "sub_cat"),
                            ("brand", "brand"),
                            ("product", "product"),
                        ],
                        max_length=8,
                    ),
                ),
                ("coupon_code", models.CharField(max_length=6)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("in_percentage", "in_percentage"),
                            ("in_rupees", "in_rupees"),
                        ],
                        max_length=15,
                    ),
                ),
                ("discount", models.IntegerField()),
                ("description", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
