# Generated by Django 4.1 on 2022-09-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_coupon_valid_till"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="bank",
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name="coupon",
            name="brand",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="coupon",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="coupon",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="sub_cat",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="upto",
            field=models.IntegerField(default=None),
        ),
    ]
